[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fixprice_api"
dynamic = ["version"]
description = "Аснинхронный неофициальный API клиент для сайта fix-price.com"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Miskler", email = "mail@miskler.ru" }
]
keywords = [
    "fixprice",
    "api",
    "browser",
    "catalog"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet",
    "Topic :: Utilities"
]
dependencies = [
    "camoufox[geoip]",
    "human_requests",
    "Pillow",
    "rich",
    "aiohttp",
    "aiohttp-retry",
    "pydantic"
]
[tool.mypy]
ignore_missing_imports = true
[tool.ruff]
line-length = 200

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM"
]
ignore = [
    "RUF001",
    "RUF002",
    "RUF003"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
fixprice_api = ["extractors/*.js", "extractors/**/*.js"]

[tool.setuptools.dynamic]
version = { attr = "fixprice_api.__version__" }

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["*_test.py", "*_tests.py"]
filterwarnings = [
    "ignore::pytest.PytestUnraisableExceptionWarning",
    "ignore:Event loop is closed:RuntimeWarning",
]
anyio_mode = "auto"
autotest_start_class = "fixprice_api.FixPriceAPI"
addopts = "-v --tb=short --disable-warnings"
